### ISSUE TITLE
Documentation doesn't reflect code

### ISSUE THREAD

**Issue by vipassana** [micolous/geojsontools#2]
The commands on the README for gtfs2geojson.py don't reflect changes in the code. I've made change on my fork and will send a pull request if that's alright with you. (https://github.com/vipassana/geojsontools)

Also, there is a missing comma in geojsonify and gtfs2geojson doesn't support decimal type. I've made change to fix those as well.

**Comment by jleape** [comment]
Thank you @vipassana !
